Add a library for executing processes
lxea/teleport_challenge pull request #2
Opened 2021-09-29 08:34 UTC by lxea

This adds a library called 'executor'. It implements the library as described in the design doc. It also includes some tests and some test shell scripts.

The shell scripts don't do anything special and should work with any standard POSIX shell.

2021-09-29 21:55 UTC, timothyb89 requested changes

2021-09-30 07:29 UTC, lxea commented on executor/executor.go
> +		path := filepath.Join(e.logDir, name.String())
I've tried to resolve this, however i think this is something that can happen no matter what -- or at least I'm not aware of a simple fix. 

As it stands os.Create will truncate a file if it already exists, what I'm trying to do here is stop it from overwriting its own log files it may have created, but I think if another application is writing to this applications log directory It shouldn't expect its files to not get destroyed

2021-10-01 00:07 UTC, tcsc commented on executor/executor.go
> +		stdoutPath := filepath.Join(e.logDir, name.String()+".stdout")
Rather than have two things that need to be unique (and have the possibility that you might half-succeed and pollute your ID space with unused IDs), how about changing this to create a directory, and use that single point as your clashing ID test? The streams could then be files inside that?

2021-10-01 01:17 UTC, russjones commented on executor/executor.go
> +		stdoutPath := filepath.Join(e.logDir, name.String()+".stdout")
I like this, in-fact I think you can simplify more, you're unlikely to ever get a UUIDv4 collision. So just generate the random UUID, mkdir, create the files and return. No need to loop 20 times trying to find something that works.

2021-10-01 01:17 UTC, russjones commented on executor/executor.go
> +	e.RUnlock()
This is fine and works, since you have to repeat this is in other functions as well, I'd do:

```go
func (e *Executor) getJob(id uuid.UUID) (*proc, error) {
	e.mu.RLock()
	defer e.mu.RUnlock()

	p, ok := e.processes[id]
	if !ok {
		return nil, fmt.Errorf("not found")
	}

	return p, nil
}
```

2021-10-01 08:17 UTC, lxea commented on executor/executor.go
> +		stdoutPath := filepath.Join(e.logDir, name.String()+".stdout")
This is a much nicer solution, it is much much cleaner than before!

2021-10-01 11:51 UTC, tcsc commented on executor/executor_test.go
> +	if err := os.MkdirAll("./logs", fs.ModePerm); err != nil {
`t.TempDir()` might be your friend here.

2021-10-01 16:44 UTC, russjones approved these changes

2021-10-01 18:20 UTC, timothyb89 approved these changes
A couple of small comments, but looks good otherwise!

2021-10-01 18:20 UTC, timothyb89 commented on executor/executor.go
> +	if os.IsExist(err) {
Looks like the error handling case here is different than the one above for stdout. Is that the desired behavior? As is I think we could end up "successfully" returning a nil pointer for stderr if some other error popped up (but maybe this is fine in practice).

2021-10-01 18:20 UTC, timothyb89 commented on executor/executor.go
> +func (e *Executor) getUUID() (uuid.UUID, *os.File, *os.File, error) {
Small nitpick, but I'd say `getUUID()` no longer really describes the tasks this function is performing.

2021-10-01 18:24 UTC, lxea commented on executor/executor.go
> +	if os.IsExist(err) {
Ah that wasnt intended, just a leftover

2021-10-01 18:27 UTC, merged